<?php
namespace aloud_core\api\components;

class Cors extends \yii\filters\Cors
{

    public function prepareHeaders($requestHeaders)
    {
        return parent::prepareHeaders($requestHeaders); // TODO: Change the autogenerated stub
    }

}