<?php
/**
 * Created by PhpStorm.
 * User: aloud
 * Date: 07.02.2018
 * Time: 23:38
 */

namespace app\models\filters;


use common\models\forms\FilterForm;

class GroupsFilter extends FilterForm
{

    public function applyFilter(&$query)
    {

        $query->andWhere(['like', 'LOWER(name)', mb_strtolower($this->search, "UTF-8")]);

        parent::applyFilter($query); // TODO: Change the autogenerated stub
    }

}